name: native_toolchain_cmake
description: >-
  A library to invoke CMake for Dart Native Assets.
version: 0.0.3
repository: https://github.com/rainyl/native_toolchain_cmake

topics:
  - cmake
  - ffi
  - native-assets
  - native-toolchain

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  change_case: ^2.2.0
  glob: ^2.1.1
  logging: ^1.1.1
  meta: ^1.9.1
  native_assets_cli: ^0.11.0
  path: ^1.9.1
  pub_semver: ^2.1.3

dev_dependencies:
  test: ^1.21.0
  collection: ^1.19.1
