name: native_toolchain_cmake
description: >-
  A library to invoke and build CMake projects for Dart Native Assets.
version: 0.2.1
repository: https://github.com/rainyl/native_toolchain_cmake

topics:
  - cmake
  - ffi
  - native-assets
  - native-toolchain

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  change_case: ^2.2.0
  code_assets: ">=1.0.0 <2.0.0"
  glob: ^2.1.3
  hooks: ">=1.0.0 <2.0.0"
  logging: ^1.3.0
  meta: ^1.16.0
  path: ^1.9.1
  pub_semver: ^2.2.0

dev_dependencies:
  collection: ^1.19.1
  test: ^1.21.0
  mocktail: ^1.0.3
