name: add
description: A sample showing how to use the native_toolchain_cmake package.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  native_toolchain_cmake:
    path: ../..
  logging: ^1.3.0
  hooks: ">=1.0.0 <2.0.0"
  code_assets: ">=1.0.0 <2.0.0"

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  ffigen: ^18.1.0

hooks:
  user_defines:
    add:
      env_file: null # ".env"
      cmake_version: null # "3.22.1"
      ninja_version: null # "1.10.2"
      prefer_android_cmake: null # true # defaults to true for android
      prefer_android_ninja: null # true # defaults to true for android
      android:
        android_home: null # "C:\\Android\\Sdk" # can be set in .env file
        ndk_version: null # "28.2.13676358"
