name: add
description: A sample showing how to use the native_toolchain_cmake package.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  native_toolchain_cmake:
    path: ../..
  logging: ^1.3.0
  native_assets_cli: ^0.11.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  ffigen: ^16.1.0
